export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_FAIL = "USER_GET_FAIL";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";

export const USER_GET1_REQUEST = "USER_GET1_REQUEST";
export const USER_GET1_FAIL = "USER_GET1_FAIL";
export const USER_GET1_SUCCESS = "USER_GET1_SUCCESS";